source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "kamal", require: false
gem "thruster", require: false

# Serialisation
gem "jsonapi-serializer"

# Background jobs
gem "sidekiq", "~> 8.0"
gem "redis", "~> 5.0"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "standardrb"
end

group :test do
  gem "rswag-specs"
  gem "shoulda-matchers"
end
