source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

gem "rails", "~> 7.0.4", ">= 7.0.4.2"
gem "puma", "~> 5.0"
gem "rack-cors"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Serialisation
gem "jsonapi-serializer"

# Background jobs
gem "sidekiq", "~> 7.0"
gem "redis", "~> 5.0"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "standardrb"
end

group :test do
  gem "rswag-specs"
  gem "shoulda-matchers"
end
